### ISSUE TITLE
API calls when delete account

### ISSUE THREAD

**Issue by RyanCheungJF** [CS3219-AY2223S1/cs3219-project-ay2223s1-g35#35]
Was doing the review service backend and realized we didn't consider what should be the expected behaviour when a user deletes their account for the backend. Would other databases such as room delete past entries or keep them? etc

**Comment by Silvernitro** [comment]
Things to delete:
- Matching-service room
  - Redis cache doesn't need to be cleared. A user's pending match in Redis only exists while he/she is spinning on the 'finding match' dialog. To delete his/her account, a user would have had to close the dialog first, which would already clear his/her entry in Redis.
- Collab-service room (needs room id from matching-service to know what to delete)
  - Redis cache doesn't need to be cleared as we read from the DB and not Redis when initializing a room + the entries in Redis will expire anyway

Things not deleted:
- Reviews (regardless of reviewer or reviewee)
